version: '2.1'
services:
  trilium:
    image: zadam/trilium
    restart: always
    ports:
      - "8080:8080"
    environment:
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
      - TZ=Asia/Shanghai
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./trilium-data:/home/node/trilium-data
